nelmio_api_doc:
    documentation:
        openapi: 3.0.0
        info:
            title: Moje API
            description: This is an awesome app!
            version: 1.0.0
        components:
            securitySchemes:
                cookieAuth:
                    type: apiKey
                    in: cookie
                    name: vue_api_token
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - cookieAuth: []
            - Bearer: []
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc
